import ResponseTool as MyTool
import queue


class FindWork(object):

	def __init__(self):
		self.citys = self.get_url()
		self.MyTool = MyTool.ResponseTool()
		self.url_queue = queue.Queue(888)

	def get_url(self):
		"""
		返回各城市链接
		:return:
		"""
		pro_citys = {
	"citys": {
		"热门城市": ["北京-https://bj.58.com/", "上海-https://sh.58.com/", "广州-https://gz.58.com/", "深圳-https://sz.58.com/", "成都-https://cd.58.com/", "杭州-https://hz.58.com/", "南京-https://nj.58.com/", "天津-https://tj.58.com/", "武汉-https://wh.58.com/", "重庆-https://cq.58.com/"],
		"安徽": ["合肥-https://hf.58.com/job/", "芜湖-https://wuhu.58.com/job/", "蚌埠-https://bengbu.58.com/job/", "阜阳-https://fy.58.com/job/", "淮南-https://hn.58.com/job/", "安庆-https://anqing.58.com/job/", "宿州-https://suzhou.58.com/job/", "六安-https://la.58.com/job/", "淮北-https://huaibei.58.com/job/", "滁州-https://chuzhou.58.com/job/", "马鞍山-https://mas.58.com/job/", "铜陵-https://tongling.58.com/job/", "宣城-https://xuancheng.58.com/job/", "亳州-https://bozhou.58.com/job/", "黄山-https://huangshan.58.com/job/", "池州-https://chizhou.58.com/job/", "巢湖-https://ch.58.com/job/", "和县-https://hexian.58.com/job/", "霍邱-https://hq.58.com/job/", "桐城-https://tongcheng.58.com/job/", "宁国-https://ningguo.58.com/job/", "天长-https://tianchang.58.com/job/", "东至-https://dongzhi.58.com/job/", "无为-https://wuweixian.58.com/job/"],
		"福建": ["福州-https://fz.58.com/job/", "厦门-https://xm.58.com/job/", "泉州-https://qz.58.com/job/", "莆田-https://pt.58.com/job/", "漳州-https://zhangzhou.58.com/job/", "宁德-https://nd.58.com/job/", "三明-https://sm.58.com/job/", "南平-https://np.58.com/job/", "龙岩-https://ly.58.com/job/", "武夷山-https://wuyishan.58.com/job/", "石狮-https://shishi.58.com/job/", "晋江-https://jinjiangshi.58.com/job/", "南安-https://nananshi.58.com/job/", "龙海-https://longhai.58.com/job/", "上杭-https://shanghangxian.58.com/job/", "福安-https://fuanshi.58.com/job/", "福鼎-https://fudingshi.58.com/job/", "安溪-https://anxixian.58.com/job/", "永春-https://yongchunxian.58.com/job/", "永安-https://yongan.58.com/job/", "漳浦-https://zhangpu.58.com/job/"],
		"广东": ["深圳-https://sz.58.com/job/", "广州-https://gz.58.com/job/", "东莞-https://dg.58.com/job/", "佛山-https://fs.58.com/job/", "中山-https://zs.58.com/job/", "珠海-https://zh.58.com/job/", "惠州-https://huizhou.58.com/job/", "江门-https://jm.58.com/job/", "汕头-https://st.58.com/job/", "湛江-https://zhanjiang.58.com/job/", "肇庆-https://zq.58.com/job/", "茂名-https://mm.58.com/job/", "揭阳-https://jy.58.com/job/", "梅州-https://mz.58.com/job/", "清远-https://qingyuan.58.com/job/", "阳江-https://yj.58.com/job/", "韶关-https://sg.58.com/job/", "河源-https://heyuan.58.com/job/", "云浮-https://yf.58.com/job/", "汕尾-https://sw.58.com/job/", "潮州-https://chaozhou.58.com/job/", "台山-https://taishan.58.com/job/", "阳春-https://yangchun.58.com/job/", "顺德-https://sd.58.com/job/", "惠东-https://huidong.58.com/job/", "博罗-https://boluo.58.com/job/", "海丰-https://haifengxian.58.com/job/", "开平-https://kaipingshi.58.com/job/", "陆丰-https://lufengshi.58.com/job/"],
		"广西": ["南宁-https://nn.58.com/job/", "柳州-https://liuzhou.58.com/job/", "桂林-https://gl.58.com/job/", "玉林-https://yulin.58.com/job/", "梧州-https://wuzhou.58.com/job/", "北海-https://bh.58.com/job/", "贵港-https://gg.58.com/job/", "钦州-https://qinzhou.58.com/job/", "百色-https://baise.58.com/job/", "河池-https://hc.58.com/job/", "来宾-https://lb.58.com/job/", "贺州-https://hezhou.58.com/job/", "防城港-https://fcg.58.com/job/", "崇左-https://chongzuo.58.com/job/", "桂平-https://guipingqu.58.com/job/", "北流-https://beiliushi.58.com/job/", "博白-https://bobaixian.58.com/job/", "岑溪-https://cenxi.58.com/job/"],
		"贵州": ["贵阳-https://gy.58.com/job/", "遵义-https://zunyi.58.com/job/", "黔东南-https://qdn.58.com/job/", "黔南-https://qn.58.com/job/", "六盘水-https://lps.58.com/job/", "毕节-https://bijie.58.com/job/", "铜仁-https://tr.58.com/job/", "安顺-https://anshun.58.com/job/", "黔西南-https://qxn.58.com/job/", "仁怀-https://renhuaishi.58.com/job/", "清镇-https://qingzhen.58.com/job/"],
		"甘肃": ["兰州-https://lz.58.com/job/", "天水-https://tianshui.58.com/job/", "白银-https://by.58.com/job/", "庆阳-https://qingyang.58.com/job/", "平凉-https://pl.58.com/job/", "酒泉-https://jq.58.com/job/", "张掖-https://zhangye.58.com/job/", "武威-https://wuwei.58.com/job/", "定西-https://dx.58.com/job/", "金昌-https://jinchang.58.com/job/", "陇南-https://ln.58.com/job/", "临夏-https://linxia.58.com/job/", "嘉峪关-https://jyg.58.com/job/", "甘南-https://gn.58.com/job/", "敦煌-https://dunhuang.58.com/job/"],
		"海南": ["海口-https://haikou.58.com/job/", "三亚-https://sanya.58.com/job/", "五指山-https://wzs.58.com/job/", "三沙-https://sansha.58.com/job/", "琼海-https://qh.58.com/job/", "文昌-https://wenchang.58.com/job/", "万宁-https://wanning.58.com/job/", "屯昌-https://tunchang.58.com/job/", "琼中-https://qiongzhong.58.com/job/", "陵水-https://lingshui.58.com/job/", "东方-https://df.58.com/job/", "定安-https://da.58.com/job/", "澄迈-https://cm.58.com/job/", "保亭-https://baoting.58.com/job/", "白沙-https://baish.58.com/job/", "儋州-https://danzhou.58.com/job/"],
		"河南": ["郑州-https://zz.58.com/job/", "洛阳-https://luoyang.58.com/job/", "新乡-https://xx.58.com/job/", "南阳-https://ny.58.com/job/", "许昌-https://xc.58.com/job/", "平顶山-https://pds.58.com/job/", "安阳-https://ay.58.com/job/", "焦作-https://jiaozuo.58.com/job/", "商丘-https://sq.58.com/job/", "开封-https://kaifeng.58.com/job/", "濮阳-https://puyang.58.com/job/", "周口-https://zk.58.com/job/", "信阳-https://xy.58.com/job/", "驻马店-https://zmd.58.com/job/", "漯河-https://luohe.58.com/job/", "三门峡-https://smx.58.com/job/", "鹤壁-https://hb.58.com/job/", "济源-https://jiyuan.58.com/job/", "明港-https://mg.58.com/job/", "鄢陵-https://yanling.58.com/job/", "禹州-https://yuzhou.58.com/job/", "长葛-https://changge.58.com/job/", "灵宝-https://lingbaoshi.58.com/job/", "杞县-https://qixianqu.58.com/job/", "汝州-https://ruzhou.58.com/job/", "项城-https://xiangchengshi.58.com/job/", "偃师-https://yanshiqu.58.com/job/", "长垣-https://changyuan.58.com/job/", "滑县-https://huaxian.58.com/job/", "林州-https://linzhou.58.com/job/", "沁阳-https://qinyang.58.com/job/", "孟州-https://mengzhou.58.com/job/", "温县-https://wenxian.58.com/job/", "尉氏-https://weishixian.58.com/job/", "兰考-https://lankaoxian.58.com/job/", "通许-https://tongxuxian.58.com/job/", "新安-https://lyxinan.58.com/job/", "伊川-https://yichuan.58.com/job/", "孟津-https://mengjinqu.58.com/job/", "宜阳-https://lyyiyang.58.com/job/", "舞钢-https://wugang.58.com/job/", "永城-https://yongcheng.58.com/job/", "睢县-https://suixian.58.com/job/", "鹿邑-https://luyi.58.com/job/", "渑池-https://yingchixian.58.com/job/", "沈丘-https://shenqiu.58.com/job/", "太康-https://taikang.58.com/job/", "商水-https://shangshui.58.com/job/", "淇县-https://qixianq.58.com/job/", "浚县-https://junxian.58.com/job/", "范县-https://fanxian.58.com/job/", "固始-https://gushixian.58.com/job/", "淮滨-https://huaibinxian.58.com/job/", "邓州-https://dengzhou.58.com/job/", "新野-https://xinye.58.com/job/"],
		"黑龙江": ["哈尔滨-https://hrb.58.com/job/", "大庆-https://dq.58.com/job/", "齐齐哈尔-https://qqhr.58.com/job/", "牡丹江-https://mdj.58.com/job/", "绥化-https://suihua.58.com/job/", "佳木斯-https://jms.58.com/job/", "鸡西-https://jixi.58.com/job/", "双鸭山-https://sys.58.com/job/", "鹤岗-https://hegang.58.com/job/", "黑河-https://heihe.58.com/job/", "伊春-https://yich.58.com/job/", "七台河-https://qth.58.com/job/", "大兴安岭-https://dxal.58.com/job/", "安达-https://shanda.58.com/job/", "肇东-https://shzhaodong.58.com/job/", "肇州-https://zhaozhou.58.com/job/"],
		"湖北": ["武汉-https://wh.58.com/job/", "宜昌-https://yc.58.com/job/", "襄阳-https://xf.58.com/job/", "荆州-https://jingzhou.58.com/job/", "十堰-https://shiyan.58.com/job/", "黄石-https://hshi.58.com/job/", "孝感-https://xiaogan.58.com/job/", "黄冈-https://hg.58.com/job/", "恩施-https://es.58.com/job/", "荆门-https://jingmen.58.com/job/", "咸宁-https://xianning.58.com/job/", "鄂州-https://ez.58.com/job/", "随州-https://suizhou.58.com/job/", "潜江-https://qianjiang.58.com/job/", "天门-https://tm.58.com/job/", "仙桃-https://xiantao.58.com/job/", "神农架-https://snj.58.com/job/", "宜都-https://yidou.58.com/job/", "汉川-https://hanchuan.58.com/job/", "枣阳-https://zaoyang.58.com/job/", "武穴-https://wuxueshi.58.com/job/", "钟祥-https://zhongxiangshi.58.com/job/", "京山-https://jingshanxian.58.com/job/", "沙洋-https://shayangxian.58.com/job/", "松滋-https://songzi.58.com/job/", "广水-https://guangshuishi.58.com/job/", "赤壁-https://chibishi.58.com/job/", "老河口-https://laohekou.58.com/job/", "谷城-https://gucheng.58.com/job/", "宜城-https://yichengshi.58.com/job/", "南漳-https://nanzhang.58.com/job/", "云梦-https://yunmeng.58.com/job/", "安陆-https://anlu.58.com/job/", "大悟-https://dawu.58.com/job/", "孝昌-https://xiaochang.58.com/job/", "当阳-https://dangyang.58.com/job/", "枝江-https://zhijiang.58.com/job/", "嘉鱼-https://jiayuxian.58.com/job/", "随县-https://suixia.58.com/job/"],
		"湖南": ["长沙-https://cs.58.com/job/", "株洲-https://zhuzhou.58.com/job/", "益阳-https://yiyang.58.com/job/", "常德-https://changde.58.com/job/", "衡阳-https://hy.58.com/job/", "湘潭-https://xiangtan.58.com/job/", "岳阳-https://yy.58.com/job/", "郴州-https://chenzhou.58.com/job/", "邵阳-https://shaoyang.58.com/job/", "怀化-https://hh.58.com/job/", "永州-https://yongzhou.58.com/job/", "娄底-https://ld.58.com/job/", "湘西-https://xiangxi.58.com/job/", "张家界-https://zjj.58.com/job/", "醴陵-https://liling.58.com/job/", "澧县-https://lixian.58.com/job/", "桂阳-https://czguiyang.58.com/job/", "资兴-https://zixing.58.com/job/", "永兴-https://yongxing.58.com/job/", "常宁-https://changningshi.58.com/job/", "祁东-https://qidongxian.58.com/job/", "衡东-https://hengdong.58.com/job/", "冷水江-https://lengshuijiangshi.58.com/job/", "涟源-https://lianyuanshi.58.com/job/", "双峰-https://shuangfengxian.58.com/job/", "邵阳县-https://shaoyangxian.58.com/job/", "邵东-https://shaodongxian.58.com/job/", "沅江-https://yuanjiangs.58.com/job/", "南县-https://nanxian.58.com/job/", "祁阳-https://qiyang.58.com/job/", "湘阴-https://xiangyin.58.com/job/", "华容-https://huarong.58.com/job/", "慈利-https://cilixian.58.com/job/", "攸县-https://zzyouxian.58.com/job/"],
		"河北": ["石家庄-https://sjz.58.com/job/", "保定-https://bd.58.com/job/", "唐山-https://ts.58.com/job/", "廊坊-https://lf.58.com/job/", "邯郸-https://hd.58.com/job/", "秦皇岛-https://qhd.58.com/job/", "沧州-https://cangzhou.58.com/job/", "邢台-https://xt.58.com/job/", "衡水-https://hs.58.com/job/", "张家口-https://zjk.58.com/job/", "承德-https://chengde.58.com/job/", "定州-https://dingzhou.58.com/job/", "馆陶-https://gt.58.com/job/", "张北-https://zhangbei.58.com/job/", "赵县-https://zx.58.com/job/", "正定-https://zd.58.com/job/", "迁安市-https://qianan.58.com/job/", "任丘-https://renqiu.58.com/job/", "三河-https://sanhe.58.com/job/", "武安-https://wuan.58.com/job/", "雄安新区-https://xionganxinqu.58.com/job/", "燕郊-https://lfyanjiao.58.com/job/", "涿州-https://zhuozhou.58.com/job/", "河间-https://hejian.58.com/job/", "黄骅-https://huanghua.58.com/job/", "沧县-https://cangxian.58.com/job/", "磁县-https://cixian.58.com/job/", "涉县-https://shexian.58.com/job/", "霸州-https://bazhou.58.com/job/", "香河-https://xianghe.58.com/job/", "固安-https://lfguan.58.com/job/", "遵化市-https://zunhua.58.com/job/", "迁西-https://qianxixian.58.com/job/", "玉田-https://yutianxian.58.com/job/", "滦南-https://luannanxian.58.com/job/", "沙河-https://shaheshi.58.com/job/"],
		"江苏": ["苏州-https://su.58.com/job/", "南京-https://nj.58.com/job/", "无锡-https://wx.58.com/job/", "常州-https://cz.58.com/job/", "徐州-https://xz.58.com/job/", "南通-https://nt.58.com/job/", "扬州-https://yz.58.com/job/", "盐城-https://yancheng.58.com/job/", "淮安-https://ha.58.com/job/", "连云港-https://lyg.58.com/job/", "泰州-https://taizhou.58.com/job/", "宿迁-https://suqian.58.com/job/", "镇江-https://zj.58.com/job/", "沭阳-https://shuyang.58.com/job/", "大丰-https://dafeng.58.com/job/", "如皋-https://rugao.58.com/job/", "启东-https://qidong.58.com/job/", "溧阳-https://liyang.58.com/job/", "海门-https://haimen.58.com/job/", "东海-https://donghai.58.com/job/", "扬中-https://yangzhong.58.com/job/", "兴化-https://xinghuashi.58.com/job/", "新沂-https://xinyishi.58.com/job/", "泰兴-https://taixing.58.com/job/", "如东-https://rudong.58.com/job/", "邳州-https://pizhou.58.com/job/", "沛县-https://xzpeixian.58.com/job/", "靖江-https://jingjiang.58.com/job/", "建湖-https://jianhu.58.com/job/", "海安-https://haian.58.com/job/", "东台-https://dongtai.58.com/job/", "丹阳-https://danyang.58.com/job/", "宝应县-https://baoyingx.58.com/job/", "灌南-https://guannan.58.com/job/", "灌云-https://guanyun.58.com/job/", "姜堰-https://jiangyan.58.com/job/", "金坛-https://jintan.58.com/job/", "昆山-https://szkunshan.58.com/job/", "泗洪-https://sihong.58.com/job/", "泗阳-https://siyang.58.com/job/", "句容-https://jurong.58.com/job/", "射阳-https://sheyang.58.com/job/", "阜宁-https://funingxian.58.com/job/", "响水-https://xiangshui.58.com/job/", "盱眙-https://xuyi.58.com/job/", "金湖-https://jinhu.58.com/job/"],
		"江西": ["南昌-https://nc.58.com/job/", "赣州-https://ganzhou.58.com/job/", "九江-https://jj.58.com/job/", "宜春-https://yichun.58.com/job/", "吉安-https://ja.58.com/job/", "上饶-https://sr.58.com/job/", "萍乡-https://px.58.com/job/", "抚州-https://fuzhou.58.com/job/", "景德镇-https://jdz.58.com/job/", "新余-https://xinyu.58.com/job/", "鹰潭-https://yingtan.58.com/job/", "永新-https://yxx.58.com/job/", "乐平-https://lepingshi.58.com/job/", "进贤-https://jinxian.58.com/job/", "分宜-https://fenyi.58.com/job/", "丰城-https://fengchengshi.58.com/job/", "樟树-https://zhangshu.58.com/job/", "高安-https://gaoan.58.com/job/", "余江-https://yujiang.58.com/job/", "南城-https://nanchengx.58.com/job/", "浮梁-https://fuliangxian.58.com/job/"],
		"吉林": ["长春-https://cc.58.com/job/", "吉林-https://jl.58.com/job/", "四平-https://sp.58.com/job/", "延边-https://yanbian.58.com/job/", "松原-https://songyuan.58.com/job/", "白城-https://bc.58.com/job/", "通化-https://th.58.com/job/", "白山-https://baishan.58.com/job/", "辽源-https://liaoyuan.58.com/job/", "公主岭-https://gongzhuling.58.com/job/", "梅河口-https://meihekou.58.com/job/", "扶余-https://fuyuxian.58.com/job/", "长岭-https://changlingxian.58.com/job/", "桦甸-https://huadian.58.com/job/", "磐石-https://panshi.58.com/job/", "梨树县-https://lishu.58.com/job/"],
		"辽宁": ["沈阳-https://sy.58.com/job/", "大连-https://dl.58.com/job/", "鞍山-https://as.58.com/job/", "锦州-https://jinzhou.58.com/job/", "抚顺-https://fushun.58.com/job/", "营口-https://yk.58.com/job/", "盘锦-https://pj.58.com/job/", "朝阳-https://cy.58.com/job/", "丹东-https://dandong.58.com/job/", "辽阳-https://liaoyang.58.com/job/", "本溪-https://benxi.58.com/job/", "葫芦岛-https://hld.58.com/job/", "铁岭-https://tl.58.com/job/", "阜新-https://fx.58.com/job/", "庄河-https://pld.58.com/job/", "瓦房店-https://wfd.58.com/job/", "灯塔-https://dengta.58.com/job/", "凤城-https://fengcheng.58.com/job/", "北票-https://beipiao.58.com/job/", "开原-https://kaiyuan.58.com/job/"],
		"宁夏": ["银川-https://yinchuan.58.com/job/", "吴忠-https://wuzhong.58.com/job/", "石嘴山-https://szs.58.com/job/", "中卫-https://zw.58.com/job/", "固原-https://guyuan.58.com/job/"],
		"内蒙古": ["呼和浩特-https://hu.58.com/job/", "包头-https://bt.58.com/job/", "赤峰-https://chifeng.58.com/job/", "鄂尔多斯-https://erds.58.com/job/", "通辽-https://tongliao.58.com/job/", "呼伦贝尔-https://hlbe.58.com/job/", "巴彦淖尔市-https://bycem.58.com/job/", "乌兰察布-https://wlcb.58.com/job/", "锡林郭勒-https://xl.58.com/job/", "兴安盟-https://xam.58.com/job/", "乌海-https://wuhai.58.com/job/", "阿拉善盟-https://alsm.58.com/job/", "海拉尔-https://hlr.58.com/job/"],
		"青海": ["西宁-https://xn.58.com/job/", "海西-https://hx.58.com/job/", "海北-https://haibei.58.com/job/", "果洛-https://guoluo.58.com/job/", "海东-https://haidong.58.com/job/", "黄南-https://huangnan.58.com/job/", "玉树-https://ys.58.com/job/", "海南-https://hainan.58.com/job/", "格尔木-https://geermushi.58.com/job/"],
		"山东": ["青岛-https://qd.58.com/job/", "济南-https://jn.58.com/job/", "烟台-https://yt.58.com/job/", "潍坊-https://wf.58.com/job/", "临沂-https://linyi.58.com/job/", "淄博-https://zb.58.com/job/", "济宁-https://jining.58.com/job/", "泰安-https://ta.58.com/job/", "聊城-https://lc.58.com/job/", "威海-https://weihai.58.com/job/", "枣庄-https://zaozhuang.58.com/job/", "德州-https://dz.58.com/job/", "日照-https://rizhao.58.com/job/", "东营-https://dy.58.com/job/", "菏泽-https://heze.58.com/job/", "滨州-https://bz.58.com/job/", "莱芜-https://lw.58.com/job/", "章丘-https://zhangqiu.58.com/job/", "垦利-https://kl.58.com/job/", "诸城-https://zc.58.com/job/", "寿光-https://shouguang.58.com/job/", "龙口-https://longkou.58.com/job/", "曹县-https://caoxian.58.com/job/", "单县-https://shanxian.58.com/job/", "肥城-https://feicheng.58.com/job/", "高密-https://gaomi.58.com/job/", "广饶-https://guangrao.58.com/job/", "桓台-https://huantaixian.58.com/job/", "莒县-https://juxian.58.com/job/", "莱州-https://laizhou.58.com/job/", "蓬莱-https://penglai.58.com/job/", "青州-https://qingzhou.58.com/job/", "荣成-https://rongcheng.58.com/job/", "乳山-https://rushan.58.com/job/", "滕州-https://tengzhou.58.com/job/", "新泰-https://xintai.58.com/job/", "招远-https://zhaoyuan.58.com/job/", "邹城-https://zoucheng.58.com/job/", "邹平-https://zouping.58.com/job/", "临清-https://linqing.58.com/job/", "茌平-https://chiping.58.com/job/", "郓城-https://hzyc.58.com/job/", "博兴-https://boxing.58.com/job/", "东明-https://dongming.58.com/job/", "巨野-https://juye.58.com/job/", "无棣-https://wudi.58.com/job/", "齐河-https://qihe.58.com/job/", "微山-https://weishan.58.com/job/", "禹城-https://yuchengshi.58.com/job/", "临邑-https://linyixianq.58.com/job/", "乐陵-https://leling.58.com/job/", "莱阳-https://laiyang.58.com/job/", "宁津-https://ningjin.58.com/job/", "高唐-https://gaotang.58.com/job/", "莘县-https://shenxian.58.com/job/", "阳谷-https://yanggu.58.com/job/", "冠县-https://guanxian.58.com/job/", "平邑-https://pingyi.58.com/job/", "郯城-https://tancheng.58.com/job/", "沂源-https://yiyuanxian.58.com/job/", "汶上-https://wenshang.58.com/job/", "梁山-https://liangshanx.58.com/job/", "利津-https://lijin.58.com/job/", "沂南-https://yinanxian.58.com/job/", "栖霞-https://qixia.58.com/job/", "宁阳-https://ningyang.58.com/job/", "东平-https://dongping.58.com/job/", "昌邑-https://changyishi.58.com/job/", "安丘-https://anqiu.58.com/job/", "昌乐-https://changle.58.com/job/", "临朐-https://linqu.58.com/job/", "鄄城-https://juancheng.58.com/job/"],
		"山西": ["太原-https://ty.58.com/job/", "临汾-https://linfen.58.com/job/", "大同-https://dt.58.com/job/", "运城-https://yuncheng.58.com/job/", "晋中-https://jz.58.com/job/", "长治-https://changzhi.58.com/job/", "晋城-https://jincheng.58.com/job/", "阳泉-https://yq.58.com/job/", "吕梁-https://lvliang.58.com/job/", "忻州-https://xinzhou.58.com/job/", "朔州-https://shuozhou.58.com/job/", "临猗-https://linyixian.58.com/job/", "清徐-https://qingxu.58.com/job/", "柳林-https://liulin.58.com/job/", "高平-https://gaoping.58.com/job/", "泽州-https://zezhou.58.com/job/", "襄垣-https://xiangyuanxian.58.com/job/", "孝义-https://xiaoyi.58.com/job/"],
		"陕西": ["西安-https://xa.58.com/job/", "咸阳-https://xianyang.58.com/job/", "宝鸡-https://baoji.58.com/job/", "渭南-https://wn.58.com/job/", "汉中-https://hanzhong.58.com/job/", "榆林-https://yl.58.com/job/", "延安-https://yanan.58.com/job/", "安康-https://ankang.58.com/job/", "商洛-https://sl.58.com/job/", "铜川-https://tc.58.com/job/", "神木-https://shenmu.58.com/job/", "韩城-https://hancheng.58.com/job/", "府谷-https://fugu.58.com/job/", "靖边-https://jingbian.58.com/job/", "定边-https://dingbian.58.com/job/"],
		"四川": ["成都-https://cd.58.com/job/", "绵阳-https://mianyang.58.com/job/", "德阳-https://deyang.58.com/job/", "南充-https://nanchong.58.com/job/", "宜宾-https://yb.58.com/job/", "自贡-https://zg.58.com/job/", "乐山-https://ls.58.com/job/", "泸州-https://luzhou.58.com/job/", "达州-https://dazhou.58.com/job/", "内江-https://scnj.58.com/job/", "遂宁-https://suining.58.com/job/", "攀枝花-https://panzhihua.58.com/job/", "眉山-https://ms.58.com/job/", "广安-https://ga.58.com/job/", "资阳-https://zy.58.com/job/", "凉山-https://liangshan.58.com/job/", "广元-https://guangyuan.58.com/job/", "雅安-https://ya.58.com/job/", "巴中-https://bazhong.58.com/job/", "阿坝-https://ab.58.com/job/", "甘孜-https://ganzi.58.com/job/", "安岳-https://anyuexian.58.com/job/", "广汉-https://guanghanshi.58.com/job/", "简阳-https://jianyangshi.58.com/job/", "仁寿-https://renshouxian.58.com/job/", "射洪-https://shehongxian.58.com/job/", "大竹-https://dazu.58.com/job/", "宣汉-https://xuanhan.58.com/job/", "渠县-https://qux.58.com/job/", "长宁-https://changningx.58.com/job/"],
		"新疆": ["乌鲁木齐-https://xj.58.com/job/", "昌吉-https://changji.58.com/job/", "巴音郭楞-https://bygl.58.com/job/", "伊犁-https://yili.58.com/job/", "阿克苏-https://aks.58.com/job/", "喀什-https://ks.58.com/job/", "哈密-https://hami.58.com/job/", "克拉玛依-https://klmy.58.com/job/", "博尔塔拉-https://betl.58.com/job/", "吐鲁番-https://tlf.58.com/job/", "和田-https://ht.58.com/job/", "石河子-https://shz.58.com/job/", "克孜勒苏-https://kzls.58.com/job/", "阿拉尔-https://ale.58.com/job/", "五家渠-https://wjq.58.com/job/", "图木舒克-https://tmsk.58.com/job/", "库尔勒-https://kel.58.com/job/", "阿勒泰-https://alt.58.com/job/", "塔城-https://tac.58.com/job/"],
		"西藏": ["拉萨-https://lasa.58.com/job/", "日喀则-https://rkz.58.com/job/", "山南-https://sn.58.com/job/", "林芝-https://linzhi.58.com/job/", "昌都-https://changdu.58.com/job/", "那曲-https://nq.58.com/job/", "阿里-https://al.58.com/job/", "日土-https://rituxian.58.com/job/", "改则-https://gaizexian.58.com/job/"],
		"云南": ["昆明-https://km.58.com/job/", "曲靖-https://qj.58.com/job/", "大理-https://dali.58.com/job/", "红河-https://honghe.58.com/job/", "玉溪-https://yx.58.com/job/", "丽江-https://lj.58.com/job/", "文山-https://ws.58.com/job/", "楚雄-https://cx.58.com/job/", "西双版纳-https://bn.58.com/job/", "昭通-https://zt.58.com/job/", "德宏-https://dh.58.com/job/", "普洱-https://pe.58.com/job/", "保山-https://bs.58.com/job/", "临沧-https://lincang.58.com/job/", "迪庆-https://diqing.58.com/job/", "怒江-https://nujiang.58.com/job/", "弥勒-https://milexian.58.com/job/", "安宁-https://anningshi.58.com/job/", "宣威-https://xuanwushi.58.com/job/"],
		"浙江": ["杭州-https://hz.58.com/job/", "宁波-https://nb.58.com/job/", "温州-https://wz.58.com/job/", "金华-https://jh.58.com/job/", "嘉兴-https://jx.58.com/job/", "台州-https://tz.58.com/job/", "绍兴-https://sx.58.com/job/", "湖州-https://huzhou.58.com/job/", "丽水-https://lishui.58.com/job/", "衢州-https://quzhou.58.com/job/", "舟山-https://zhoushan.58.com/job/", "乐清-https://yueqingcity.58.com/job/", "瑞安-https://ruiancity.58.com/job/", "义乌-https://yiwu.58.com/job/", "余姚-https://yuyao.58.com/job/", "诸暨-https://zhuji.58.com/job/", "象山-https://xiangshanxian.58.com/job/", "温岭-https://wenling.58.com/job/", "桐乡-https://tongxiang.58.com/job/", "慈溪-https://cixi.58.com/job/", "长兴-https://changxing.58.com/job/", "嘉善-https://jiashanx.58.com/job/", "海宁-https://haining.58.com/job/", "德清-https://deqing.58.com/job/", "东阳-https://dongyang.58.com/job/", "安吉-https://anji.58.com/job/", "苍南-https://cangnanxian.58.com/job/", "临海-https://linhai.58.com/job/", "永康-https://yongkang.58.com/job/", "玉环-https://yuhuan.58.com/job/", "平湖-https://pinghushi.58.com/job/", "海盐-https://haiyan.58.com/job/", "武义县-https://wuyix.58.com/job/", "嵊州-https://shengzhou.58.com/job/", "新昌-https://xinchang.58.com/job/", "江山-https://jiangshanshi.58.com/job/", "平阳-https://pingyangxian.58.com/job/"],
		"其他": ["香港-https://hk.58.com/job/", "澳门-https://am.58.com/job/", "台湾-https://tw.58.com/job/", "全国-https://quanguo.58.com/job/", "其他-https://cn.58.com/job/"],
		"海外": ["洛杉矶-https://g.58.com/j-gllosangeles/", "旧金山-https://g.58.com/j-glsanfrancisco/", "纽约-https://g.58.com/j-glnewyork/", "多伦多-https://g.58.com/j-gltoronto/", "温哥华-https://g.58.com/j-glvancouver/", "伦敦-https://g.58.com/j-glgreaterlondon/", "莫斯科-https://g.58.com/j-glmoscow/", "首尔-https://g.58.com/j-glseoul/", "东京-https://g.58.com/j-gltokyo/", "新加坡-https://g.58.com/j-glsingapore/", "曼谷-https://g.58.com/j-glbangkok/", "清迈-https://g.58.com/j-glchiangmai/", "迪拜-https://g.58.com/j-gldubai/", "奥克兰-https://g.58.com/j-glauckland/", "悉尼-https://g.58.com/j-glsydney/", "墨尔本-https://g.58.com/j-glmelbourne/", "其他海外城市-https://g.58.com/city/"],
	}
}
		return pro_citys


